--- #YAML:1.0
name:               SWISH-3
version:            0.11
abstract:           Perl interface to libswish3
author:
    - Peter Karman <perl@peknet.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dump:  0
    perl:        5.008003
    Test::More:  0
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/Bugs.html?Dist=SWISH-3
    homepage:    http://dev.swish-e.org/wiki/swish3
    license:     GPL
    repository:  http://svn.swish-e.org/libswish3
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
